import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

class DevicePairingService {
  final SupabaseClient supabase = Supabase.instance.client;

  /// Verifies 6-Digit Pairing Code generated by Desktop App
  Future<Map<String, dynamic>> verifyPairingCode(String code, String fcmToken, String deviceName) async {
    try {
      final cleanCode = code.trim();
      debugPrint("[Pairing] Verifying code: $cleanCode against Supabase...");

      final response = await supabase
          .from('device_pairings')
          .select()
          .eq('pair_code', cleanCode)
          .maybeSingle();

      if (response == null) {
        debugPrint("[Pairing] Code not found in device_pairings table");
        return {"success": false, "message": "Code not found. Generate a new code from Desktop POS."};
      }

      if (response['status'] != 'pending') {
        return {"success": false, "message": "This code has already been used. Generate a fresh code."};
      }

      // Check expiration
      final expiresAt = DateTime.parse(response['expires_at']);
      if (DateTime.now().toUtc().isAfter(expiresAt.toUtc())) {
        return {"success": false, "message": "Code expired. Please generate a new code from Desktop POS."};
      }

      final deviceUuid = response['device_uuid'] as String? ?? 'default_desktop';

      // Update pairing status & bind FCM token
      try {
        await supabase.from('device_pairings').update({
          'status': 'paired',
          'fcm_token': fcmToken,
          'device_name': deviceName,
        }).eq('pair_code', cleanCode);
      } catch (updErr) {
        debugPrint("[Pairing] Status update note: $updErr");
      }

      // Save pairing state and device_uuid locally
      final prefs = await SharedPreferences.getInstance();
      await prefs.setBool('is_paired', true);
      await prefs.setString('paired_code', cleanCode);
      await prefs.setString('paired_device_uuid', deviceUuid);

      debugPrint("[Pairing] Successfully paired with desktop device_uuid: $deviceUuid");
      return {"success": true, "message": "Device paired successfully!"};
    } on PostgrestException catch (pe) {
      debugPrint("[Pairing] Supabase PostgrestException: ${pe.message} (${pe.code})");
      if (pe.code == 'PGRST205' || pe.message.contains('device_pairings')) {
        return {"success": false, "message": "Table 'device_pairings' missing in Supabase. Run the SQL in Supabase SQL Editor."};
      }
      return {"success": false, "message": "Database error: ${pe.message}"};
    } catch (e) {
      debugPrint("[Pairing] Verification error: $e");
      return {"success": false, "message": "Verification failed: $e"};
    }
  }

  Future<bool> isDevicePaired() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getBool('is_paired') ?? false;
  }

  Future<String?> getPairedDeviceUuid() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString('paired_device_uuid');
  }

  Future<void> unpairDevice() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove('is_paired');
    await prefs.remove('paired_code');
    await prefs.remove('paired_device_uuid');
  }
}
