import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';

class DevicePairingService {
  final SupabaseClient supabase = Supabase.instance.client;

  /// Verifies 6-Digit Pairing Code generated by Desktop App
  Future<bool> verifyPairingCode(String code, String fcmToken, String deviceName) async {
    try {
      final response = await supabase
          .from('device_pairings')
          .select()
          .eq('pair_code', code)
          .eq('status', 'pending')
          .maybeSingle();

      if (response == null) {
        return false;
      }

      // Check expiration
      final expiresAt = DateTime.parse(response['expires_at']);
      if (DateTime.now().isAfter(expiresAt)) {
        return false;
      }

      // Update pairing status & bind FCM token
      await supabase.from('device_pairings').update({
        'status': 'paired',
        'fcm_token': fcmToken,
        'device_name': deviceName,
      }).eq('pair_code', code);

      // Save pairing state locally
      final prefs = await SharedPreferences.getInstance();
      await prefs.setBool('is_paired', true);
      await prefs.setString('paired_code', code);

      return true;
    } catch (e) {
      return false;
    }
  }

  Future<bool> isDevicePaired() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getBool('is_paired') ?? false;
  }
}
